language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t renatoelric/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true renatoelric/react-test npm test -- --coverage

after_success:
    - docker build -t renatoelric/complex-client ./client
    - docker build -t renatoelric/complex-nginx ./nginx
    - docker build -t renatoelric/complex-server ./server
    - docker build -t renatoelric/complex-worker ./worker

    #Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push renatoelric/complex-client
    - docker push renatoelric/complex-nginx
    - docker push renatoelric/complex-server
    - docker push renatoelric/complex-worker 